### ISSUE TITLE
Update link color on 2017/schedules/

### ISSUE THREAD

**Issue by maxrugen** [fsr/ese-website#76]
Recognizing links on the Stundenpläne site could be significantly easier if 
```css
a:visited {
  color: #323232;
}
```
would be used instead of 
```css
a:visited {
  color: #0b5283;
}
a:hover {
  color: #323232;
}
```
